// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmNW1O11nBfx2zF_NC0ftACJ2lP64QMs',
    appId: '1:649918761667:web:fc12e4d798effb2a437076',
    messagingSenderId: '649918761667',
    projectId: 'todo-app-c11-96502',
    authDomain: 'todo-app-c11-96502.firebaseapp.com',
    storageBucket: 'todo-app-c11-96502.appspot.com',
    measurementId: 'G-KBWC86TDB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvRw9FwVyfB4NP1QzP6I5i2d5AQ30cYkI',
    appId: '1:649918761667:android:fc1091639ea4e36d437076',
    messagingSenderId: '649918761667',
    projectId: 'todo-app-c11-96502',
    storageBucket: 'todo-app-c11-96502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaKmLpbSzhCk3QzBaX3yGDFHgieEaDLxs',
    appId: '1:649918761667:ios:47b12497152e4475437076',
    messagingSenderId: '649918761667',
    projectId: 'todo-app-c11-96502',
    storageBucket: 'todo-app-c11-96502.appspot.com',
    iosBundleId: 'com.example.todoC11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaKmLpbSzhCk3QzBaX3yGDFHgieEaDLxs',
    appId: '1:649918761667:ios:47b12497152e4475437076',
    messagingSenderId: '649918761667',
    projectId: 'todo-app-c11-96502',
    storageBucket: 'todo-app-c11-96502.appspot.com',
    iosBundleId: 'com.example.todoC11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmNW1O11nBfx2zF_NC0ftACJ2lP64QMs',
    appId: '1:649918761667:web:882542320b846844437076',
    messagingSenderId: '649918761667',
    projectId: 'todo-app-c11-96502',
    authDomain: 'todo-app-c11-96502.firebaseapp.com',
    storageBucket: 'todo-app-c11-96502.appspot.com',
    measurementId: 'G-9C3DCXEJHY',
  );

}